export enum cryptoTypes {
  FETCH_CRYPTO_REQUEST = 'FETCH_CRYPTO_REQUEST',
  GET_CRYPTO_DATA = 'GET_CRYPTO_DATA',
  GET_CRYPTO_SUCCESS = 'GET_CRYPTO_SUCCESS',
  GET_CRYPTO_FAIL = 'GET_CRYPTO_FAIL',
  SORT_TABLE_ACTION = 'SORT_TABLE_ACTION',
  START_LOADING = 'START_LOADING',
  END_LOADING = 'END_LOADING',
  ADD_CRYPTO_TO_WATCHLIST = 'ADD_CRYPTO_TO_WATCHLIST',
  REMOVE_CRYPTO_FROM_WATCHLIST = 'REMOVE_CRYPTO_FROM_WATCHLIST',
}
