export enum cryptoTypes {
  FETCH_CRYPTO_REQUEST = 'FETCH_CRYPTO_REQUEST',
  FETCH_CRYPTO_SUCCESS = 'FETCH_CRYPTO_SUCCESS',
  FETCH_CRYPTO_FAIL = 'FETCH_CRYPTO_FAIL',
  SORT_TABLE_ACTION = 'SORT_TABLE_ACTION',
  START_CRYPTO_LOADING = 'START_CRYPTO_LOADING',
  END_CRYPTO_LOADING = 'END_CRYPTO_LOADING',
  ADD_CRYPTO_TO_WATCHLIST = 'ADD_CRYPTO_TO_WATCHLIST',
  REMOVE_CRYPTO_FROM_WATCHLIST = 'REMOVE_CRYPTO_FROM_WATCHLIST',
}
